### PR TITLE
Simplify authentication

### PR DESCRIPTION
**Pull request by athornton**

### CODE REVIEW

**Review by rra — CHANGES_REQUESTED** [review]
You should not set cookie when the code doesn't send a cookie.

I'm not sure why you're dropping all of the configuration for specific URLs. I think this will mean that PyVO will start promiscuously sending the credentials to every site it tries to contact, including things entirely outside the RSP, which would be a security vulnerability.

**Comment by athornton** [comment]
Changing this to draft until the capabilities are rolled out to prod--this will not work with old-style TAP, but once environments are new-style we can merge and cut a new release.

**Comment by athornton** [comment]
I may have misinterpreted what @stvoutsin was saying in https://github.com/lsst-sqre/lsst-tap-service/pull/110 -- I read that as "drop specific URL support".

**Comment by athornton** [comment]
and of course if this is totally the wrong way to go about it I'm happy to do it the right way--I just don't know what that is

**Comment by stvoutsin** [comment]
I think using the lsst-token is valid and fine, there is perhaps merit and simplifying and using VO supported methods, but it seems like the only ones currently supported in pyvo are:
```
ANONYMOUS = 'anonymous'
BASIC = 'ivo://ivoa.net/sso#BasicAA'
CLIENT_CERTIFICATE = 'ivo://ivoa.net/sso#tls-with-certificate'
COOKIE = 'ivo://ivoa.net/sso#cookie'
```
https://github.com/astropy/pyvo/blob/main/pyvo/auth/securitymethods.py
We could perhaps PR additional methods like "OAuth" to pyvo if that is what we want.
What pyvo should then be doing I think is reading the capabilities and creating the mapping of endpoints to security methods from that. Which in theory should do what the extra calls to register each endpoint is doing. In practice, as we've seen with the results fetching it treats that as authenticated, perhaps because of a potential gap in the standard of registering whether /results is authenticated. (Maybe you can do that with the standard, I'd have to read up on it)

**Comment by athornton** [comment]
OK, closing unmerged and marking the parent ticket as `Invalid`.  If there's anything we DO need to do in lsst.rsp in order to support the newer capabilities stuff, lmk.

**Pull request closed without merging**
